[package]
name = "azure-functions-shared"
license = "MIT"
version = "0.2.2"
authors = ["Peter Huene <peterhuene@protonmail.com>"]
description = "Implementations shared between the azure-functions-codegen and azure-functions crates."
repository = "https://github.com/peterhuene/azure-functions-rs/"

[package.metadata.docs.rs]
features = ["cached_protobufs"]

[dependencies]
azure-functions-shared-codegen = { version = "0.2.2", path = "../azure-functions-shared-codegen" }
protobuf = "2.0.5"
grpcio = "0.4.0"
futures = "0.1.24"
serde = "1.0.79"
serde_derive = "1.0.79"

[build-dependencies]
protoc-grpcio = "0.2.1"
reqwest = "0.9.2"

[features]
default = []
cached_protobufs = []
