[package]
name = "azure-functions-shared"
license = "MIT"
version = "0.7.0"
authors = ["Peter Huene <peterhuene@protonmail.com>"]
description = "Implementations shared between the azure-functions-codegen and azure-functions crates."
repository = "https://github.com/peterhuene/azure-functions-rs/"
homepage = "https://functions.rs"
edition = "2018"

[dependencies]
azure-functions-shared-codegen = { version = "0.7.0", path = "../azure-functions-shared-codegen" }
tower-grpc = { git = "https://github.com/tower-rs/tower-grpc", rev = "55d004e49f6c6097a9f556752bceb8b32c8c700f"}
prost = "0.5"
prost-types = "0.5"
bytes = "0.4"
serde = "1.0.91"
serde_json = "1.0.39"
serde_derive = "1.0.90"
quote = "0.6.12"
syn = { version = "0.15.33", features = ["full"] }
proc-macro2 = { version = "0.4.29" }
lazy_static = "1.3.0"

[build-dependencies]
tower-grpc-build = { git = "https://github.com/tower-rs/tower-grpc", rev = "55d004e49f6c6097a9f556752bceb8b32c8c700f"}

[features]
default = []
compile_protobufs = []
unstable = ["azure-functions-shared-codegen/unstable"]
