[package]
name = "azure-functions-shared"
license = "MIT"
version = "0.3.0"
authors = ["Peter Huene <peterhuene@protonmail.com>"]
description = "Implementations shared between the azure-functions-codegen and azure-functions crates."
repository = "https://github.com/peterhuene/azure-functions-rs/"
homepage = "https://functions.rs"
edition = "2018"

[dependencies]
azure-functions-shared-codegen = { version = "0.3.0", path = "../azure-functions-shared-codegen" }
protobuf = "2.0.5"
grpcio = "0.4.1"
futures = "0.1.24"
serde = "1.0.84"
serde_derive = "1.0.85"

[build-dependencies]
protoc-grpcio = "0.3.1"

[features]
default = []
compile_protobufs = []