[package]
name = "azure-functions-shared"
license = "MIT"
version = "0.5.2"
authors = ["Peter Huene <peterhuene@protonmail.com>"]
description = "Implementations shared between the azure-functions-codegen and azure-functions crates."
repository = "https://github.com/peterhuene/azure-functions-rs/"
homepage = "https://functions.rs"
edition = "2018"

[dependencies]
azure-functions-shared-codegen = { version = "0.5.2", path = "../azure-functions-shared-codegen" }
protobuf = "2.3.0"
grpcio = { version = "0.4.4", default-features = false, features = ["protobuf-codec"] }
futures = "0.1.24"
serde = "1.0.89"
serde_json = "1.0.39"
serde_derive = "1.0.89"
quote = "0.6.11"
syn = { version = "0.15.29", features = ["full"] }
proc-macro2 = { version = "0.4.27" }
lazy_static = "1.3.0"

[build-dependencies]
protoc-grpcio = "1.0.1"

[features]
default = []
compile_protobufs = []
unstable = ["azure-functions-shared-codegen/unstable"]
