[package]
name = "example-timer"
version = "0.1.0"
authors = ["Peter Huene <peterhuene@protonmail.com>"]

[dependencies]
azure-functions = { version = "0.2.4", path = "../../azure-functions" }
log = "0.4.6"
