[package]
name = "azure-functions-sdk"
license = "MIT"
version = "0.3.0"
authors = ["Peter Huene <peterhuene@protonmail.com>"]
description = "Azure Functions for Rust Developer Tools"
repository = "https://github.com/peterhuene/azure-functions-rs/"
homepage = "https://functions.rs"
edition = "2018"

[[bin]]
name = "cargo-func"
path = "src/main.rs"

[dependencies]
colored = "1.7"
clap = "2.31.2"
atty = "0.2.11"
handlebars = "1.1.0"
serde_json = "1.0.38"
toml = "0.4.10"