[package]
name = "example-queue"
version = "0.1.0"
authors = ["Peter Huene <peterhuene@protonmail.com>"]

[dependencies]
azure-functions = { version = "0.2.1", path = "../../azure-functions" }
log = "0.4.5"
