[package]
name = "example-http"
version = "0.1.0"
authors = ["Peter Huene <peterhuene@protonmail.com>"]

[dependencies]
azure-functions = { version = "0.2.4", path = "../../azure-functions" }
log = "0.4.6"
serde = "1.0.79"
serde_json = "1.0.33"
serde_derive = "1.0.79"
