[package]
name = "example-http"
version = "0.1.0"
authors = ["Peter Huene <peterhuene@protonmail.com>"]

[dependencies]
azure-functions = { version = "0.2.2", path = "../../azure-functions" }
log = "0.4.5"
serde = "1.0.79"
serde_json = "1.0.31"
serde_derive = "1.0.79"
