[package]
name = "http-example"
version = "0.1.0"
authors = ["Peter Huene <peterhuene@protonmail.com>"]
edition = "2018"

[dependencies]
azure-functions = { path = "../../azure-functions" }
log = "0.4.6"
serde = { version = "1.0.87", features = ["derive"] }
serde_json = "1.0.38"
