[package]
name = "azure-functions-codegen"
license = "MIT"
version = "0.2.4"
authors = ["Peter Huene <peterhuene@protonmail.com>"]
description = "Azure Functions for Rust code generation support"
repository = "https://github.com/peterhuene/azure-functions-rs/"
homepage = "https://functions.rs"

[lib]
proc-macro = true

[dependencies]
azure-functions-shared = { version = "0.2.4", path = "../azure-functions-shared" }
quote = "0.6.10"
syn = { version = "0.15.20", features = ["full"] }
proc-macro2 = { version = "0.4.23", features = ["nightly"] }
lazy_static = "1.2.0"
