[package]
name = "example-table"
version = "0.1.0"
authors = ["Peter Huene <peterhuene@protonmail.com>"]

[dependencies]
azure-functions = { version = "0.1.6", path = "../../azure-functions" }
serde_json = "1.0.21"