[package]
name = "table-example"
version = "0.1.0"
authors = ["Peter Huene <peterhuene@protonmail.com>"]
edition = "2018"

[dependencies]
azure-functions = "0.3.0"
log = "0.4.6"
serde_json = "1.0.37"
