[package]
name = "azure-functions-shared-codegen"
license = "MIT"
version = "0.1.4"
authors = ["Peter Huene <peterhuene@protonmail.com>"]
description = "Code generation for the azure-functions-shared crate."
repository = "https://github.com/peterhuene/azure-functions-rs/"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.3"
syn = { version = "0.14.2", features = ["full"] }
